FROM flink:latest

# Create CLI Lib folder
RUN mkdir -p /opt/sql-client/lib

# Copy sql-client.sh to /opt/sql-client
COPY sql-client.sh /opt/sql-client/



# Download connector libraries
RUN wget -P /opt/sql-client/lib/ https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.4.0-1.20/flink-sql-connector-kafka-3.4.0-1.20.jar  ;\
    wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.19/flink-connector-jdbc-3.2.0-1.19.jar ; \
    wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/1.20.0/flink-json-1.20.0.jar ;\
    wget -P /opt/sql-client/lib/ https://jdbc.postgresql.org/download/postgresql-42.5.4.jar && \
    wget -P /opt/sql-client/lib/ https://repo1.maven.org/maven2/org/apache/flink/flink-sql-avro-confluent-registry/1.20.0/flink-sql-avro-confluent-registry-1.20.0.jar


RUN wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.4.0-1.20/flink-sql-connector-kafka-3.4.0-1.20.jar  ;\
    wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.19/flink-connector-jdbc-3.2.0-1.19.jar ; \
    wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/1.20.0/flink-json-1.20.0.jar ;\
    wget -P /opt/flink/lib/ https://jdbc.postgresql.org/download/postgresql-42.5.4.jar && \
    wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/org/apache/flink/flink-sql-avro-confluent-registry/1.20.0/flink-sql-avro-confluent-registry-1.20.0.jar
    
WORKDIR /opt/sql-client
ENV SQL_CLIENT_HOME /opt/sql-client

#COPY docker-entrypoint.sh /opt/sql-client
#RUN chmod +x /opt/sql-client/docker-entrypoint.sh
#ENTRYPOINT ["/opt/sql-client/docker-entrypoint.sh"]